# Generated by Django 3.2.16 on 2023-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230913_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='\n        Идентификатор страницы для URL; разрешены символы\n        латиницы, цифры, дефис и подчёркивание.\n        ', unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='\n        Если установить дату и время в будущем — можно делать\n        отложенные публикации.\n        ', verbose_name='Дата и время публикации'),
        ),
    ]
