# Generated by Django 3.2.16 on 2023-09-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230926_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='\nЕсли установить дату и время в будущем — можно делать отложенные публикации.\n        ', verbose_name='Дата и время публикации'),
        ),
    ]
